'use client'

import { useEffect, useState } from 'react'
import { getJobs, createJob } from '@/lib/api'
import { useAuth } from '@/components/AuthProvider'
import JobCard from '@/components/JobCard'

export default function JobsPage() {
  const { user } = useAuth()
  const [jobs, setJobs] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [creating, setCreating] = useState(false)
  const [createError, setCreateError] = useState<string | null>(null)
  const [formData, setFormData] = useState({ title: '', description: '', rubric_path: '', hiring_manager_email: '' })

  const fetchJobs = async () => { try { setLoading(true); setError(null); setJobs(await getJobs()) } catch (err: any) { setError(err.message || 'Failed') } finally { setLoading(false) } }
  const handleCreateJob = async (e: React.FormEvent) => {
    e.preventDefault(); setCreating(true); setCreateError(null)
    try { await createJob({ title: formData.title, description: formData.description, rubric_path: formData.rubric_path, hiring_manager_email: formData.hiring_manager_email || undefined }); setFormData({ title: '', description: '', rubric_path: '', hiring_manager_email: '' }); setIsCreateModalOpen(false); await fetchJobs() } catch (err: any) { setCreateError(err.message || 'Failed') } finally { setCreating(false) }
  }
  useEffect(() => { fetchJobs() }, [])

  if (loading) return (<div className="flex items-center justify-center min-h-[60vh]"><div className="text-center"><div className="relative w-16 h-16 mx-auto mb-6"><div className="absolute inset-0 rounded-full border-2 animate-spin" style={{ borderColor: 'var(--cyan-electric)', borderTopColor: 'transparent' }} /></div><p className="font-mono text-sm uppercase tracking-wider" style={{ color: 'var(--navy-mid)' }}>Loading positions...</p></div></div>)
  if (error) return (<div className="max-w-2xl mx-auto mt-12"><div className="border-l-4 p-8" style={{ borderColor: 'var(--coral-warm)', background: 'rgba(255, 107, 107, 0.05)' }}><h3 className="font-display text-xl mb-2" style={{ color: 'var(--navy-deep)' }}>Error</h3><p className="mb-4" style={{ color: 'var(--navy-mid)' }}>{error}</p><button onClick={fetchJobs} className="px-6 py-2 font-medium text-sm" style={{ background: 'var(--coral-warm)', color: 'white' }}>Try Again</button></div></div>)

  return (
    <div className="max-w-7xl mx-auto px-6 lg:px-12 py-16">
      <div className="mb-16"><div className="flex items-start justify-between gap-8 mb-8"><div className="flex-1"><div className="font-mono text-xs uppercase tracking-wider mb-4" style={{ color: 'var(--navy-mid)' }}>Job Management</div><h1 className="font-display text-5xl lg:text-6xl leading-tight mb-6" style={{ color: 'var(--navy-deep)' }}>Manage Positions</h1><p className="text-xl leading-relaxed max-w-2xl" style={{ color: 'var(--navy-light)' }}>View and manage all job postings. Monitor candidate pipelines and track hiring progress.</p></div><div className="hidden lg:flex flex-col gap-4"><button onClick={() => setIsCreateModalOpen(true)} className="px-6 py-3 font-medium transition-all hover:opacity-90" style={{ background: 'var(--cyan-electric)', color: 'var(--navy-deep)' }}>+ Create New Job</button>{jobs.length > 0 && (<div className="accent-line pl-6"><div className="font-display text-4xl mb-2" style={{ color: 'var(--cyan-electric)' }}>{jobs.length}</div><div className="font-mono text-xs uppercase tracking-wider" style={{ color: 'var(--navy-mid)' }}>{jobs.length === 1 ? 'Position' : 'Positions'}</div></div>)}</div></div><div className="h-px" style={{ background: 'var(--warm-gray)' }} /></div>
      {jobs.length === 0 ? (<div className="text-center py-24"><h3 className="font-display text-2xl mb-3" style={{ color: 'var(--navy-deep)' }}>No Open Positions</h3><p className="text-lg max-w-md mx-auto" style={{ color: 'var(--navy-light)' }}>No job postings yet. Create your first position to start screening candidates.</p></div>) : (<div className="grid grid-cols-1 lg:grid-cols-2 gap-8">{jobs.map((job, index) => (<div key={job.id} className="reveal-up" style={{ animationDelay: `${index * 0.1}s` }}><JobCard job={job} isAdmin={!!user} /></div>))}</div>)}
      {isCreateModalOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(10, 22, 40, 0.8)' }} onClick={() => setIsCreateModalOpen(false)}><div className="max-w-2xl w-full border-l-4 p-8" style={{ borderColor: 'var(--cyan-electric)', background: 'white', maxHeight: '90vh', overflowY: 'auto' }} onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between mb-8"><div><h2 className="font-display text-3xl mb-2" style={{ color: 'var(--navy-deep)' }}>Create New Job</h2></div><button onClick={() => setIsCreateModalOpen(false)} className="p-2" style={{ color: 'var(--navy-mid)' }}>✕</button></div>{createError && (<div className="mb-6 p-4 border-l-4" style={{ borderColor: 'var(--coral-warm)' }}><p style={{ color: 'var(--coral-warm)' }}>{createError}</p></div>)}<form onSubmit={handleCreateJob} className="space-y-6"><div><label className="block font-medium mb-3 text-sm uppercase tracking-wider" style={{ color: 'var(--navy-mid)' }}>Job Title *</label><input type="text" required value={formData.title} onChange={(e) => setFormData({...formData, title: e.target.value})} className="w-full px-4 py-3 border-2" style={{ borderColor: 'var(--warm-gray)' }} placeholder="e.g., Senior Backend Engineer" /></div><div><label className="block font-medium mb-3 text-sm uppercase tracking-wider" style={{ color: 'var(--navy-mid)' }}>Job Description *</label><textarea required rows={6} value={formData.description} onChange={(e) => setFormData({...formData, description: e.target.value})} className="w-full px-4 py-3 border-2" style={{ borderColor: 'var(--warm-gray)' }} placeholder="Describe the role..." /></div><div><label className="block font-medium mb-3 text-sm uppercase tracking-wider" style={{ color: 'var(--navy-mid)' }}>Rubric Path *</label><input type="text" required value={formData.rubric_path} onChange={(e) => setFormData({...formData, rubric_path: e.target.value})} className="w-full px-4 py-3 border-2" style={{ borderColor: 'var(--warm-gray)' }} placeholder="rubrics/backend.md" /></div><div><label className="block font-medium mb-3 text-sm uppercase tracking-wider" style={{ color: 'var(--navy-mid)' }}>Hiring Manager Email</label><input type="email" value={formData.hiring_manager_email} onChange={(e) => setFormData({...formData, hiring_manager_email: e.target.value})} className="w-full px-4 py-3 border-2" style={{ borderColor: 'var(--warm-gray)' }} placeholder="hiring@company.com" /></div><div className="flex gap-4 pt-4"><button type="button" onClick={() => setIsCreateModalOpen(false)} className="flex-1 px-6 py-3 font-medium border-2" style={{ borderColor: 'var(--navy-deep)', color: 'var(--navy-deep)' }}>Cancel</button><button type="submit" disabled={creating} className="flex-1 px-6 py-3 font-medium disabled:opacity-50" style={{ background: creating ? 'var(--navy-mid)' : 'var(--navy-deep)', color: 'var(--off-white)' }}>{creating ? 'Creating...' : 'Create Job'}</button></div></form></div></div>)}
    </div>
  )
}
