"""
Channel-Aware Response Formatters
Phase: Incubation (TASK-006)

Formats responses appropriately for each communication channel:
- Email: Formal, detailed, with greeting/signature
- WhatsApp: Concise, conversational, with emojis
- Web Form: Semi-formal, structured, helpful
"""

from typing import Dict, Any, Optional
import re


class ResponseFormatter:
    """
    Formats AI responses for different communication channels.
    Follows brand voice guidelines from context/brand-voice.md
    """

    def __init__(self):
        """Initialize response formatter."""
        self.max_lengths = {
            'email': 2000,  # 200-500 words ≈ 1000-2500 chars
            'whatsapp': 1600,  # Twilio limit, prefer <300 chars
            'web_form': 1500  # 150-300 words ≈ 750-1500 chars
        }

    def format_response(
        self,
        content: str,
        channel: str,
        customer_name: str = "there",
        ticket_id: Optional[str] = None,
        include_ticket_reference: bool = True
    ) -> str:
        """
        Format response for specific channel.

        Args:
            content: Raw response content
            channel: Target channel (email, whatsapp, web_form)
            customer_name: Customer's name
            ticket_id: Ticket reference ID
            include_ticket_reference: Whether to include ticket reference

        Returns:
            Formatted response string
        """
        if channel == 'email':
            return self._format_email(content, customer_name, ticket_id, include_ticket_reference)
        elif channel == 'whatsapp':
            return self._format_whatsapp(content, customer_name)
        elif channel == 'web_form':
            return self._format_web_form(content, customer_name, ticket_id, include_ticket_reference)
        else:
            # Fallback to web form format
            return self._format_web_form(content, customer_name, ticket_id, include_ticket_reference)

    def _format_email(
        self,
        content: str,
        customer_name: str,
        ticket_id: Optional[str],
        include_ticket_reference: bool
    ) -> str:
        """
        Format response for email channel.

        Style: Formal, detailed, professional
        Structure: Greeting → Body → Closing → Signature → Ticket Reference
        Length: 200-500 words
        """
        # Build email structure
        parts = []

        # Greeting
        parts.append(f"Dear {customer_name},")
        parts.append("")

        # Body content
        parts.append(content)
        parts.append("")

        # Closing offer
        if not self._has_closing_offer(content):
            parts.append("Is there anything else I can help you with today?")
            parts.append("")

        # Signature
        parts.append("Best regards,")
        parts.append("TechCorp AI Support Team")
        parts.append("")

        # Ticket reference and AI disclosure
        footer_parts = []
        if include_ticket_reference and ticket_id:
            footer_parts.append(f"Ticket Reference: #{ticket_id}")
        footer_parts.append("This response was generated by our AI assistant.")

        parts.append("---")
        parts.append("\n".join(footer_parts))

        formatted = "\n".join(parts)

        # Ensure length is appropriate
        if len(formatted) > self.max_lengths['email']:
            formatted = self._truncate_email(formatted, self.max_lengths['email'])

        return formatted

    def _format_whatsapp(self, content: str, customer_name: str) -> str:
        """
        Format response for WhatsApp channel.

        Style: Concise, conversational, friendly
        Structure: Brief greeting → Direct answer → Quick offer
        Length: Prefer <300 chars, max 1600 chars
        """
        # Build WhatsApp message
        parts = []

        # Brief greeting (optional, only if content doesn't start with greeting)
        if not content.lower().startswith(('hi', 'hello', 'hey')):
            parts.append(f"Hi {customer_name}! 👋")
            parts.append("")

        # Main content (should already be concise)
        parts.append(content)

        # Add friendly closing if not present
        if not self._has_closing_offer(content):
            parts.append("")
            parts.append("Need more help? Just ask! 😊")

        formatted = "\n".join(parts)

        # Ensure emojis are present but not excessive
        formatted = self._adjust_emojis(formatted)

        # Truncate if too long
        if len(formatted) > self.max_lengths['whatsapp']:
            formatted = self._truncate_whatsapp(formatted, self.max_lengths['whatsapp'])

        return formatted

    def _format_web_form(
        self,
        content: str,
        customer_name: str,
        ticket_id: Optional[str],
        include_ticket_reference: bool
    ) -> str:
        """
        Format response for web form channel.

        Style: Semi-formal, structured, helpful
        Structure: Acknowledgment → Body → Resources → Offer → Reference
        Length: 150-300 words
        """
        parts = []

        # Acknowledgment
        parts.append(f"Thank you for contacting TechCorp Support, {customer_name}!")
        parts.append("")

        # Body content
        parts.append(content)
        parts.append("")

        # Closing offer if not present
        if not self._has_closing_offer(content):
            parts.append("If you need further assistance, please reply to this ticket and I'll be happy to help.")
            parts.append("")

        # Footer with ticket reference and AI disclosure
        footer_parts = []
        if include_ticket_reference and ticket_id:
            footer_parts.append(f"Ticket Reference: #{ticket_id}")
        footer_parts.append("---")
        footer_parts.append("This response was generated by our AI assistant.")

        parts.append("\n".join(footer_parts))

        formatted = "\n".join(parts)

        # Ensure length is appropriate
        if len(formatted) > self.max_lengths['web_form']:
            formatted = self._truncate_web_form(formatted, self.max_lengths['web_form'])

        return formatted

    def _has_closing_offer(self, content: str) -> bool:
        """Check if content already has a closing offer for help."""
        closing_phrases = [
            'anything else',
            'need more help',
            'further assistance',
            'let me know',
            'just ask',
            'happy to help',
            'here to help'
        ]
        content_lower = content.lower()
        return any(phrase in content_lower for phrase in closing_phrases)

    def _adjust_emojis(self, text: str) -> str:
        """
        Ensure WhatsApp messages have appropriate emoji usage.
        Add if missing, reduce if excessive.
        """
        # Count existing emojis
        emoji_pattern = re.compile(
            "["
            "\U0001F600-\U0001F64F"  # emoticons
            "\U0001F300-\U0001F5FF"  # symbols & pictographs
            "\U0001F680-\U0001F6FF"  # transport & map symbols
            "\U0001F1E0-\U0001F1FF"  # flags
            "\U00002702-\U000027B0"
            "\U000024C2-\U0001F251"
            "]+",
            flags=re.UNICODE
        )

        emoji_count = len(emoji_pattern.findall(text))

        # If no emojis and message is friendly, add one at the end
        if emoji_count == 0 and not text.endswith(('!', '?', '.')):
            text += " 😊"

        # If too many emojis (>3), it's probably fine for WhatsApp
        # but we won't add more

        return text

    def _truncate_email(self, text: str, max_length: int) -> str:
        """Truncate email while preserving structure."""
        if len(text) <= max_length:
            return text

        # Try to truncate at paragraph boundary
        truncate_at = max_length - 200  # Leave room for footer
        paragraphs = text.split('\n\n')

        truncated_parts = []
        current_length = 0

        for para in paragraphs:
            if current_length + len(para) + 2 <= truncate_at:
                truncated_parts.append(para)
                current_length += len(para) + 2
            else:
                break

        # Add truncation notice and footer
        truncated = '\n\n'.join(truncated_parts)
        truncated += "\n\n[Response truncated for length. Please see the full article in our help center.]\n\n"

        # Add back the footer
        footer_start = text.rfind('---')
        if footer_start > 0:
            truncated += text[footer_start:]

        return truncated

    def _truncate_whatsapp(self, text: str, max_length: int) -> str:
        """Truncate WhatsApp message while keeping it readable."""
        if len(text) <= max_length:
            return text

        # Truncate at sentence boundary
        truncate_at = max_length - 50
        sentences = re.split(r'([.!?]\s+)', text)

        truncated = ""
        for i in range(0, len(sentences), 2):
            sentence = sentences[i]
            if i + 1 < len(sentences):
                sentence += sentences[i + 1]

            if len(truncated) + len(sentence) <= truncate_at:
                truncated += sentence
            else:
                break

        # Add continuation notice
        truncated += "\n\n[Message truncated. Reply for more details!]"

        return truncated

    def _truncate_web_form(self, text: str, max_length: int) -> str:
        """Truncate web form response while preserving structure."""
        if len(text) <= max_length:
            return text

        # Similar to email truncation
        truncate_at = max_length - 150
        paragraphs = text.split('\n\n')

        truncated_parts = []
        current_length = 0

        for para in paragraphs:
            if current_length + len(para) + 2 <= truncate_at:
                truncated_parts.append(para)
                current_length += len(para) + 2
            else:
                break

        truncated = '\n\n'.join(truncated_parts)
        truncated += "\n\n[Response truncated. Please see our help center for complete information.]\n\n"

        # Add back footer
        footer_start = text.rfind('Ticket Reference:')
        if footer_start > 0:
            truncated += text[footer_start:]
        else:
            footer_start = text.rfind('---')
            if footer_start > 0:
                truncated += text[footer_start:]

        return truncated

    def format_with_knowledge_base(
        self,
        query: str,
        kb_results: str,
        channel: str,
        customer_name: str = "there",
        ticket_id: Optional[str] = None
    ) -> str:
        """
        Format response that includes knowledge base search results.

        Args:
            query: Original customer query
            kb_results: Formatted knowledge base search results
            channel: Target channel
            customer_name: Customer's name
            ticket_id: Ticket reference ID

        Returns:
            Formatted response with KB results
        """
        if channel == 'email':
            content = f"I found some helpful information for you:\n\n{kb_results}"
        elif channel == 'whatsapp':
            # Simplify KB results for WhatsApp
            content = self._simplify_kb_for_whatsapp(kb_results)
        else:  # web_form
            content = f"Here's what I found:\n\n{kb_results}"

        return self.format_response(content, channel, customer_name, ticket_id)

    def _simplify_kb_for_whatsapp(self, kb_results: str) -> str:
        """Simplify knowledge base results for WhatsApp's concise format."""
        # Extract just the titles and URLs
        lines = kb_results.split('\n')
        simplified = []

        for line in lines:
            if line.startswith('**') and 'relevance:' in line:
                # Extract title
                title = line.split('**')[1].split('(')[0].strip()
                simplified.append(f"📄 {title}")
            elif line.startswith('Learn more:'):
                # Extract URL
                url = line.replace('Learn more:', '').strip()
                simplified.append(url)
                simplified.append("")

        return '\n'.join(simplified[:10])  # Limit to keep it short


# Example usage and testing
if __name__ == "__main__":
    formatter = ResponseFormatter()

    # Test content
    test_content = """To reset your password, follow these steps:

1. Go to www.techcorp.com/login
2. Click "Forgot Password?"
3. Enter your email address
4. Check your inbox for the reset link
5. Click the link within 1 hour
6. Create a new password

If you don't receive the email, check your spam folder."""

    print("=" * 80)
    print("CHANNEL FORMATTING TESTS")
    print("=" * 80)

    # Test Email format
    print("\n1. EMAIL FORMAT")
    print("-" * 80)
    email_response = formatter.format_response(
        test_content,
        'email',
        'John Doe',
        '990e8400-e29b-41d4-a716-446655440006'
    )
    print(email_response)

    # Test WhatsApp format
    print("\n2. WHATSAPP FORMAT")
    print("-" * 80)
    whatsapp_response = formatter.format_response(
        test_content,
        'whatsapp',
        'John'
    )
    print(whatsapp_response)
    print(f"\nLength: {len(whatsapp_response)} characters")

    # Test Web Form format
    print("\n3. WEB FORM FORMAT")
    print("-" * 80)
    web_response = formatter.format_response(
        test_content,
        'web_form',
        'John Doe',
        '990e8400-e29b-41d4-a716-446655440006'
    )
    print(web_response)

    # Test with knowledge base results
    print("\n4. WITH KNOWLEDGE BASE RESULTS")
    print("-" * 80)

    kb_results = """**Password Reset Guide** (relevance: 0.92)
Password reset links expire after 1 hour for security reasons. To reset your password, go to Settings > Security > Reset Password...
Learn more: help.techcorp.com/password-reset

---

**Account Security Best Practices** (relevance: 0.78)
Keep your account secure by using a strong password with at least 8 characters...
Learn more: help.techcorp.com/security"""

    kb_email = formatter.format_with_knowledge_base(
        "how to reset password",
        kb_results,
        'email',
        'Sarah Chen',
        '770e8400-e29b-41d4-a716-446655440003'
    )
    print("EMAIL WITH KB:")
    print(kb_email)

    print("\n" + "-" * 80)
    kb_whatsapp = formatter.format_with_knowledge_base(
        "how to reset password",
        kb_results,
        'whatsapp',
        'Sarah'
    )
    print("\nWHATSAPP WITH KB:")
    print(kb_whatsapp)
    print(f"\nLength: {len(kb_whatsapp)} characters")

    print("\n" + "=" * 80)
