module.exports = {
  apps: [
    {
      name: 'candidate-screening-backend',
      script: '.venv/bin/uvicorn',
      args: 'main:app --host 0.0.0.0 --port 8000 --workers 1',
      cwd: '/mnt/d/hamza/autonomous-ftes/Candidate_Screening_Agent/backend',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      restart_delay: 5000,
      max_restarts: 10,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_file: './logs/backend-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'candidate-screening-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/mnt/d/hamza/autonomous-ftes/Candidate_Screening_Agent/frontend',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 10000,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_file: './logs/frontend-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'candidate-screening-admin',
      script: 'npm',
      args: 'start',
      cwd: '/mnt/d/hamza/autonomous-ftes/Candidate_Screening_Agent/frontend-admin',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 10000,
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      log_file: './logs/admin-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
};
