"""
Metadata creator for generating markdown files with YAML frontmatter.

Creates metadata files in Needs_Action folder when new files are detected.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from ..utils.file_utils import detect_file_type, get_mime_type, format_file_size
from ..utils.yaml_parser import write_file_with_frontmatter
from ..utils.obsidian_api import create_wikilink, create_tag


class MetadataCreator:
    """
    Creates metadata files for detected files.

    Metadata files are markdown with YAML frontmatter containing:
    - type: "file_drop"
    - original_name: filename
    - size: file size in bytes
    - detected_at: ISO-8601 timestamp
    - status: "pending"
    - file_type: detected category
    - mime_type: MIME type if available
    """

    def __init__(self, vault_path: Path):
        """
        Initialize MetadataCreator.

        Args:
            vault_path: Path to the vault root directory
        """
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / "Needs_Action"
        self.needs_action.mkdir(parents=True, exist_ok=True)

    def create_metadata(self, filepath: Path) -> Path:
        """
        Create a metadata file for a detected file.

        Args:
            filepath: Path to the detected file

        Returns:
            Path to the created metadata file
        """
        # Get file information
        file_stat = filepath.stat()
        file_size = file_stat.st_size
        mime_type, file_type = get_mime_type(filepath)
        detected_at = datetime.now().isoformat() + "Z"

        # Create frontmatter
        frontmatter = {
            "type": "file_drop",
            "original_name": filepath.name,
            "size": file_size,
            "detected_at": detected_at,
            "status": "pending",
            "file_type": file_type,
            "mime_type": mime_type
        }

        # Create body content
        body = self._generate_body(filepath.name, file_size, file_type)

        # Generate metadata filename
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        metadata_filename = f"FILE_{filepath.stem}_{timestamp}.md"
        metadata_path = self.needs_action / metadata_filename

        # Write metadata file
        write_file_with_frontmatter(metadata_path, frontmatter, body)

        return metadata_path

    def _generate_body(self, filename: str, size: int, file_type: str) -> str:
        """
        Generate the markdown body for the metadata file with wikilinks and tags.

        Args:
            filename: Original filename
            size: File size in bytes
            file_type: Detected file type category

        Returns:
            Markdown body content with wikilinks for graph view
        """
        size_formatted = format_file_size(size)

        # Create tags for graph view
        type_tag = create_tag(file_type)
        status_tag = create_tag("pending")

        # Create wikilinks to hub pages
        dashboard_link = create_wikilink("Dashboard")

        # Remove extension from filename for wikilink
        file_stem = filename.rsplit('.', 1)[0] if '.' in filename else filename

        body = f"""{type_tag} {status_tag}

## File Information
- **Name:** {filename}
- **Size:** {size_formatted}
- **Type:** {file_type.capitalize()}

## Navigation
- 📊 {dashboard_link} - View system status
- 📂 Original file will be in Needs_Action folder

## Suggested Actions
- [ ] Analyze content
- [ ] Create summary
- [ ] Move to Done

---
*This metadata file was auto-generated by the AI Employee system*
"""
        return body
